### ISSUE TITLE
Word: Kubernetes

### ISSUE THREAD

**Issue by alefteris** [tsevdos/greek-in-tech-site#17]
"Kubernetes is an open source container cluster manager by Google." "Kubernetes (from κυβερνήτης: Greek for "helmsman" or "pilot")". https://en.wikipedia.org/wiki/Kubernetes

**Comment by tsevdos** [comment]
:+1:

**Comment by tsevdos** [comment]
Added with this commit: 4643a8b4bcd43f05f0c55b98f80eeea10cfd08ac
