### ISSUE TITLE
Entry: Python

### ISSUE THREAD

**Issue by faysvas** [tsevdos/greek-in-tech-site#22]
In Greek mythology, Python (Greek: Πύθων, gen.: Πύθωνος) was the earth-dragon of Delphi, always represented in Greek sculpture and vase-paintings as a serpent. He presided at the Delphic oracle, which existed in the cult center for his mother, Gaia, "Earth," Pytho being the place name that was substituted for the earlier Krisa.[1] Hellenes considered the site to be the center of the earth, represented by a stone, the omphalos or navel, which Python guarded.

**Comment by tsevdos** [comment]
:+1:

**Comment by tsevdos** [comment]
Added with this commit: 4643a8b4bcd43f05f0c55b98f80eeea10cfd08ac
