### ISSUE TITLE
Entry:Delphi

### ISSUE THREAD

**Issue by faysvas** [tsevdos/greek-in-tech-site#25]
Delphi (/ˈdɛlfaɪ/ or /ˈdɛlfi/; Greek: Δελφοί, [ðelˈfi]) is both an archaeological site and a modern town in Greece on the south-western spur of Mount Parnassus in the valley of Phocis. In myths dating to the classical period of Ancient Greece (510-323 BC), the site of Delphi was believed to be determined by Zeus when he sought to find the centre of his "Grandmother Earth" (Ge, Gaea, or Gaia).

**Comment by tsevdos** [comment]
Added with this commit: 4643a8b4bcd43f05f0c55b98f80eeea10cfd08ac
