### ISSUE TITLE
Entry: Hypertext

### ISSUE THREAD

**Issue by faysvas** [tsevdos/greek-in-tech-site#27]
The English prefix hyper- comes from the Greek prefix "ὑπερ-" and means "over" or "beyond"; it has a common origin with the prefix "super-" which comes from Latin. It signifies the overcoming of the previous linear constraints of written text.

**Comment by tsevdos** [comment]
Added with this commit: 4643a8b4bcd43f05f0c55b98f80eeea10cfd08ac
