### ISSUE TITLE
Entry: Cyber

### ISSUE THREAD

**Issue by faysvas** [tsevdos/greek-in-tech-site#30]
The prefix Cyber- is derived from "cybernetic," which comes from the Greek word κυβερνητικός meaning skilled in steering or governing. It is used in the terms cyberspace, cyberpunk, cybergoth, cyberlaw, cybercrime, cyberwarfare, cyberterrorism, cybersex, and cyberbullying, among others.

**Comment by tsevdos** [comment]
Added with this commit: be2dbc6
