### ISSUE TITLE
Entry: Automaton

### ISSUE THREAD

**Issue by faysvas** [tsevdos/greek-in-tech-site#31]
The word "automaton" is the latinization of the Greek αὐτόματον, automaton, (neuter) "acting of one's own will".An automaton (plural: automata or automatons) is a self-operating machine, or a machine or control mechanism designed to follow automatically a predetermined sequence of operations, or respond to predetermined instructions.

**Comment by tsevdos** [comment]
Added with this commit: be2dbc6
