### ISSUE TITLE
Entry: Beta

### ISSUE THREAD

**Issue by faysvas** [tsevdos/greek-in-tech-site#41]
In computing, the term "beta" is used as (usually) the last testing release（or the preview release） in the software release life cycle before the "release" version. Beta (UK /ˈbiːtə/ or US /ˈbeɪtə/; uppercase Β, lowercase β, or cursive ϐ; Ancient Greek: βῆτα bḗta or Modern Greek: βήτα víta) is the second letter of the Greek alphabet.

**Comment by tsevdos** [comment]
Added with this commit: be2dbc6
