### ISSUE TITLE
Improve typography

### ISSUE THREAD

**Issue by sebdesign** [tsevdos/greek-in-tech-site#45]
Actually I can see two issues here:

a. The transliteration of greek words should be set in _italic_ type. The convention is that terms (technical, scientific, linguistic, etc.) and foreign words should be italicized for emphasis and differentiation. For example:

> The word graphics comes from the Greek _graphikos_ [...]

b. The words in greek, e.g. `γραφικός`, should be set in same typeface as the body type. The Raleway typeface does not support greek characters, therefore it falls back to Helvetica, which is not ideal. The closest typeface which looks like Raleway is Montserrat, but there's no support for greek characters on Google fonts.

The best solution is to use the fonts from the official repo: https://github.com/JulietaUla/Montserrat, which cover all the weights and languages, and can be converted to web fonts with the Font Squirrel generator or some other tool. The SIL license approves the conversion so there are no legal issues.

**Comment by dbaltas** [comment]
a. Good point about having the transliteration in italic. One concern that I have (I am not sure if John agrees) is having html in the descriptions... which currently resides in a json [file](https://github.com/tsevdos/greek-in-tech/blob/gh-pages/js/app/data/entries.json)

b. The font is something that, afaik, John is working on, any ideas are welcome though.

**Comment by sebdesign** [comment]
a. Maybe markdown is more suitable instead of html in the json values.

b. I'd be happy to help with ideas or make a PR.

**Comment by tsevdos** [comment]
Hello there @sebdesign I just recieved a PSD/design from a friend of mine, and I'm planning to change the theme next week. This will definetely fix the typography bug. Regarding storing the entries to markdown, do you know how we can implement it with our current stack Require.js/Backbone?

**Comment by sebdesign** [comment]
Hi @tsevdos! Although I don't have any experience in backbone.js or requirejs, I found these plugins: https://github.com/millermedeiros/requirejs-plugins/ which include a markdown parser.

Otherwise, inside the backbone.js template you could invoke a markdown parser like https://github.com/evilstreak/markdown-js.

Looking forward to see the new design!

**Comment by tsevdos** [comment]
The new theme is up and resolves most of the issues.

Regarding the second idea now (markdown), it's making things a lot more complicated since we must load a markdown file for each entry, something very costly (on bandwidth, parsing, etc.)

I can understand the value of the typographic elements on the description (strong, italic, cite, etc.), but loading and parsing 43 files doesn't sound a good idea as well.
