### ISSUE TITLE
Make it more social & SEO friendly

### ISSUE THREAD

**Issue by kbariotis** [tsevdos/greek-in-tech-site#48]
- [x] Favicon is a must (maybe a simple background for a start)
- [x] Social tags (Guide: https://moz.com/blog/meta-data-templates-123)
- [x] A few images of larger size (Favicon is scale for a start)
- [x] Better meta descriptions

**Comment by tsevdos** [comment]
Hello there @kbariotis 

I'm working with a graphic designer to make a new theme, so soon we'll have a favicon and maybe a logo. When the theme is ready we can continue with your suggestions.

best regards,
John

**Comment by tsevdos** [comment]
Commit : 55951e0782bc0018a9c924570508420383b4063a
