### ISSUE TITLE
Optional citation/referece field in entries

### ISSUE THREAD

**Issue by mylk** [tsevdos/greek-in-tech-site#53]
The citation/reference field would contain a URL to another website.

This could be rendered at the end of the entry in order to:
- support the argument and/or
- provide a source for further reading

Cons:
This may add some extra administrative work for verifing that the URL is correct
and that it contains info related to the word.

**Comment by dbaltas** [comment]
:+1: It can be a list of URLs to support multiple references, and it can be optional so that there is no administrative overhead

**Comment by tsevdos** [comment]
Nice suggestion. Feel free to start it ;-)

**Comment by mylk** [comment]
Cool! Please assign this to me!
