### ISSUE TITLE
Fix tests about the entries collection

### ISSUE THREAD

**Issue by mylk** [tsevdos/greek-in-tech-site#67]
Some suggestions that we discussed with @tsevdos on a previous merge request.
- the count of the entries can be left untested.
- the entry ID uniqueness test will let non-unique IDs pass the test.
  
  This can be reproduced by changing an entry ID to a non-unique, and then decrementing the range by one in that specific test case.

**Comment by mylk** [comment]
There is array in that test case ('contains entry models with unique IDs') that is filled with the entry IDs. I can think of two solutions.

This array can either:
- be sorted then iterated and check if the current ID matches the next ID,
- be tested if it equals to a clone of itself previously passed through _.uniq().

**Comment by tsevdos** [comment]
I'll check your suggestions when I'll add model tests. Currently I'm focusing on a huge refactoring (from requirejs to webpack - check webpack branch), and I'll deal with these issues after finnishing this.
