### ISSUE TITLE
Entry: Hexadecimal

### ISSUE THREAD

**Issue by faysvas** [tsevdos/greek-in-tech-site#72]
In mathematics and computing, hexadecimal (also base 16, or hex) is a positional numeral system with a radix, or base, of 16. The word hexadecimal is composed of hexa-, derived from the Greek έξ (hex) for six, and -decimal, derived from the Latin for tenth.

**Comment by tsevdos** [comment]
fixed with commit 39fd12f39ccf7dbf3e9ee60c3dad07df6dc6b73d
