### ISSUE TITLE
Entry: Protocol

### ISSUE THREAD

**Issue by faysvas** [tsevdos/greek-in-tech-site#77]
From Byzantine Greek πρωτόκολλον ‎(“first sheet glued onto a manuscript”), from πρῶτος ‎(prôtos, “first”) + κόλλα ‎(kólla, “glue”). A set of formal rules describing how to transmit or exchange data, especially across a network.

**Comment by tsevdos** [comment]
fixed with commit 39fd12f39ccf7dbf3e9ee60c3dad07df6dc6b73d
