### ISSUE TITLE
Entry: Titan

### ISSUE THREAD

**Issue by faysvas** [tsevdos/greek-in-tech-site#80]
From Ancient Greek Τιτάν ‎(Titán), a race of giant gods in Greek mythology that preceded and was overthrown by the Olympian gods.
Titan is a supercomputer built by Cray at Oak Ridge National Laboratory for use in a variety of science projects. Titan is an upgrade of Jaguar, a previous supercomputer at Oak Ridge, that uses graphics processing units (GPUs) in addition to conventional central processing units (CPUs). Titan is the first such hybrid to perform over 10 petaFLOPS.
Titan is also the name of the prototype of the Atlas 2 computer developed by Ferranti and the University of Cambridge Mathematical Laboratory in Cambridge, England. It was designed starting in 1963, and in operation from 1964 to 1973.

**Comment by tsevdos** [comment]
fixed with commit 39fd12f39ccf7dbf3e9ee60c3dad07df6dc6b73d
