### ISSUE TITLE
Entry: Paragon

### ISSUE THREAD

**Issue by faysvas** [tsevdos/greek-in-tech-site#81]
From Ancient Greek παρακονάω ‎(parakonáō, “I sharpen, whet”). 
The Intel Paragon is a discontinued series of massively parallel supercomputers that was produced by Intel in the 1990s. The Paragon XP/S is a productized version of the experimental Touchstone Delta system that was built at Caltech, launched in 1992. The Paragon superseded Intel's earlier iPSC/860 system, to which it is closely related.

**Comment by tsevdos** [comment]
fixed with commit 39fd12f39ccf7dbf3e9ee60c3dad07df6dc6b73d
