### ISSUE TITLE
Entry: Syntax

### ISSUE THREAD

**Issue by faysvas** [tsevdos/greek-in-tech-site#84]
The word syntax comes from Ancient Greek: σύνταξις "coordination", which consists of σύν syn, "together," and τάξις táxis, "an ordering".
In computer science, the syntax of a computer language is the set of rules that defines the combinations of symbols that are considered to be a correctly structured document or fragment in that language. This applies both to programming languages, where the document represents source code, and markup languages, where the document represents data.

**Comment by tsevdos** [comment]
fixed with commit 39fd12f39ccf7dbf3e9ee60c3dad07df6dc6b73d
